kind = "DojoModel"
class_hash = "0x3f309e7d10e3c4834d61e67ae0d6520a2ad51d5f0eefac21b15e27f5b034319"
original_class_hash = "0x3f309e7d10e3c4834d61e67ae0d6520a2ad51d5f0eefac21b15e27f5b034319"
abi = "manifests/dev/base/abis/models/mancala-Seed-64c952d1.json"
tag = "mancala-Seed"
qualified_path = "mancala::models::index::seed"
manifest_name = "mancala-Seed-64c952d1"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "pit_number"
type = "u8"
key = true

[[members]]
name = "seed_number"
type = "u8"
key = true

[[members]]
name = "color"
type = "SeedColor"
key = false

[[members]]
name = "seed_id"
type = "u8"
key = false
