kind = "DojoModel"
class_hash = "0x466da8580f02547d1260c65a8b93080da94b25091055834203f66b638264412"
original_class_hash = "0x466da8580f02547d1260c65a8b93080da94b25091055834203f66b638264412"
abi = "manifests/dev/base/abis/models/mancala-Pit-22175c12.json"
tag = "mancala-Pit"
qualified_path = "mancala::models::index::pit"
manifest_name = "mancala-Pit-22175c12"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "current_pit"
type = "u8"
key = true

[[members]]
name = "seed_count"
type = "u8"
key = false
