kind = "DojoContract"
class_hash = "0x1db238879c7168fa3cb75e54b73f070cc0dba2d816bdf0e2260b9c0ae4a33e0"
original_class_hash = "0x1db238879c7168fa3cb75e54b73f070cc0dba2d816bdf0e2260b9c0ae4a33e0"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/mancala-actions-5608e015.json"
reads = []
writes = []
init_calldata = []
tag = "mancala-actions"
systems = [
    "initialize_game_counter",
    "join_game",
    "timeout",
    "create_private_game",
    "move",
    "forfeited",
    "request_restart_game",
    "restart_current_game",
]
manifest_name = "mancala-actions-5608e015"
