kind = "DojoContract"
class_hash = "0x6c10505b85b8d7b7fb29dbb0428d1eb48065fbdf39fdc6058278972e3c80bde"
original_class_hash = "0x6c10505b85b8d7b7fb29dbb0428d1eb48065fbdf39fdc6058278972e3c80bde"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/mancala-actions-5608e015.json"
reads = []
writes = []
init_calldata = []
tag = "mancala-actions"
systems = [
    "initialize_game_counter",
    "join_game",
    "timeout",
    "create_private_game",
    "move",
    "forfeited",
    "request_restart_game",
    "restart_current_game",
]
manifest_name = "mancala-actions-5608e015"
