kind = "DojoContract"
class_hash = "0x1cbe19f255cfab2c3b9fd11a8c87be8aa2240f2f32d528a65332565678cd644"
original_class_hash = "0x1cbe19f255cfab2c3b9fd11a8c87be8aa2240f2f32d528a65332565678cd644"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/mancala-actions-5608e015.json"
reads = []
writes = []
init_calldata = []
tag = "mancala-actions"
systems = [
    "initialize_game_counter",
    "join_game",
    "timeout",
    "create_private_game",
    "move",
    "forfeited",
    "request_restart_game",
    "restart_current_game",
]
manifest_name = "mancala-actions-5608e015"
